v1.5.0
UMCUGenetics/Dx_tracks pull request #30
Opened 2021-08-19 10:14 UTC by melferink

Addition of SNParray tracks

2021-08-19 14:38 UTC, rernst reviewed
- CytoSNP-850Kv1-2: does not contain MT?
  - .list contains MT reference in header  
- SNParray folder name is not very explanatory. Maybe use BAF_UPD like fingerprint and ED.
- List files contain 'target' while bed files contain an id (rs and other) why not put this on the 'target' location?
- Maybe add a README describing the files and how they were created?

2021-09-16 09:04 UTC, ellendejong requested changes
Mainly wondering if you can decrease number of manual/custom bash commands by using existing tools such as Picard or GATK.

2021-09-16 09:05 UTC, ellendejong commented on Tracks/README.md
> +rm ENSEMBL_UCSC_merged_collapsed_sorted_v3_CREv2_SSv7_100bpflank_1based.bed
You can merge these three commands into a single one.

2021-09-16 10:45 UTC, melferink commented on Tracks/README.md
> +cat S31285117_Padded.bed | grep -v track |grep -v browser |sed 's/^chr//g' | awk '{OFS="\t"; print $1,$2,$3,"+", "ssv7_target","ssv7_target","ssv7_target"}' > S31285117_Padded_nochr.bed
Agree, exept the $2+1.  Conversion to 1-based will be later.

2021-09-16 11:47 UTC, melferink commented on Tracks/README.md
> +cat S31285117_Covered.bed |grep -v browser |grep -v track | sed 's/^chr//g' | awk '{OFS ="\t"; print $1,$2+1,$3,"+","SS_v7_S31285117"}' > S31285117_Covered_nochr_5kol.list
I do not agree with the substr($1,4). It's not always certain if the BED file of Agilent are "chr"  based or not.
Using substr will go wrong if it doesn't contain chr.
sed /^chr// is a saver bet in my opinion.

2021-09-16 11:49 UTC, melferink commented on Tracks/README.md
> +cat /hpc/diaggen/data/databases/ref_genomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.dict ENSEMBL_UCSC_merged_collapsed_sorted_v3_CREv2_SSv7_100bpflank_1based.bed > ENSEMBL
Agree to use Picard (despite  adding more dependencies). 
However, number of lines do not really decrease as Picard input need some massage as well ;)

2021-09-16 13:56 UTC, ellendejong approved these changes
As discussed separately, I approve these changes with two remarks.

1. In general, I prefer using tools over custom commands to clean-up code.
A specific example in this pull-request is the manual merging of bedfiles which include sorting on chromosomes and the difficulties with MT after X,Y.

1. Secondly, when using a certain file type extension, I think it is good practice to use a format guideline. For example, files within this repos / pull-request are called .bed, and format does not match these guidelines http://genome.ucsc.edu/FAQ/FAQformat#format1 . Ofcourse, this can be solved by either changing the extension to .tsv, or change the content to match.

I will add these two remarks as work items in Azure and hope we can resolve it somewhere in the near future.

2021-09-16 14:07 UTC, merged